services:
  vite-app:
    build:
      context: .
      dockerfile: ./vite-app/Dockerfile
    container_name: allshop-vite
    ports:
      - "3000:80"
    restart: unless-stopped


  nextjs-app:
    build:
      context: .
      dockerfile: ./nextjs-app/Dockerfile
    container_name: allshop-nextjs
    ports:
      - "3001:3000"
    restart: unless-stopped

  fresh-app:
    build:
      context: .
      dockerfile: ./fresh-app/Dockerfile
    container_name: allshop-fresh
    ports:
      - "3002:8000"
    restart: unless-stopped
