// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_register from "./routes/auth/register.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $index from "./routes/index.tsx";
import * as $product_id_ from "./routes/product/[id].tsx";
import * as $CartPage from "./islands/CartPage.tsx";
import * as $ChatWidget from "./islands/ChatWidget.tsx";
import * as $CheckoutPage from "./islands/CheckoutPage.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $ProductDetail from "./islands/ProductDetail.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $ScrollToTop from "./islands/ScrollToTop.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/register.tsx": $auth_register,
    "./routes/cart.tsx": $cart,
    "./routes/checkout.tsx": $checkout,
    "./routes/index.tsx": $index,
    "./routes/product/[id].tsx": $product_id_,
  },
  islands: {
    "./islands/CartPage.tsx": $CartPage,
    "./islands/ChatWidget.tsx": $ChatWidget,
    "./islands/CheckoutPage.tsx": $CheckoutPage,
    "./islands/Header.tsx": $Header,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/ProductDetail.tsx": $ProductDetail,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/ScrollToTop.tsx": $ScrollToTop,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
